
#docker-compose -f environment.yml up -d
version: '2.1'
services:
  figures:
    image: mysql:8.0.21
    ports:
    - "3316:3306"
    command: --init-file /data/application/init.sql
    volumes:
    - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: figures
      MYSQL_USER: developer

